on:
  rss:
    url: https://nitter.dark.fail/search/rss?f=tweets&q=lang%3Aja+min_faves%3A10000
    config:
      sort:
        pubDate: 1
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - run: wget https://github.com/ChaoticWeg/discord.sh/raw/master/discord.sh
      - run: chmod +x ./discord.sh
      - run: ./discord.sh \
          --webhook-url="${{ secrets.NITTER_TREND_DISCORD_WEBHOOK }}" \
          --username "Actionsflow" \
          --avatar "https://actionsflow.github.io/favicon.svg" \
          --text "${{ on.rss.outputs.link }}"
