on:
  rss:
    url: https://nitter.dark.fail/search/rss?f=tweets&q=lang%3Aja+min_faves%3A10000
    config:
      sort:
        pubDate: 1
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.NITTER_TREND_DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Actionsflow
          DISCORD_AVATAR: https://actionsflow.github.io/favicon.svg
        uses: Ilshidur/action-discord@master
        with:
          args: '${{ on.rss.outputs.link }}'
