on:
  rss:
    url: https://nitter.net/search/rss?f=tweets&q=%23%E3%82%A2%E3%82%B8%E9%AF%96+filter%3Aimages+OR+filter%3Avideos+exclude%3Aretweets
    config:
      skipFirst: false
      sort:
        pubDate: 1
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.HASHTAG_AZISABA_DISCORD_WEBHOOK }}
          method: POST
          body: |
            {
              "username": "#アジ鯖 の画像を最速で貼り付けるボット",
              "avatar_url": "https://avatars2.githubusercontent.com/u/69839062?v=4",
              "content": "${{ on.rss.outputs.link }}"
            }
