on:
  rss:
    url: https://nitter.net/search/rss?f=tweets&q=list%3A1337691182504144896+min_faves%3A500
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.SHUUMAI_DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Actionsflow
          DISCORD_AVATAR: https://avatars2.githubusercontent.com/u/69839062?v=4
        uses: Ilshidur/action-discord@master
        with:
          args: '${{ on.rss.outputs.link }}'
